version: "3"
services:
  server:
    build: ./server
    container_name: server
    ports:
      - "3001:3001"
  client:
    build: ./client
    container_name: client
    ports:
      - "80:80"
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/
