version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    container_name: server
    image: francescomedina/se2-r03-spg-server:release2
    ports:
      - "3001:3001"
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    stdin_open: true
    container_name: client
    image: francescomedina/se2-r03-spg-client:release2
    ports:
      - "3000:3000"
    depends_on:
      - server
    links:
      - server
#  sqlite3:
#    image: nouchka/sqlite3:latest
#    stdin_open: true
#    tty: true
#    volumes:
#      - ./db/:/root/db/
